apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  template:
    spec: 
      containers:
      - name: drupal
        image: cr.io/repo/mydrupal:1
        ports:
        - containerPort: 80
